### ISSUE TITLE
Crashing gemini with unknown options

### ISSUE THREAD

**Issue by zxqfox** [gemini-testing/html-reporter#14]
Not sure why unknown options crashing the whole process.

Probably it should just warn about them.

This behaviour especially annoying on various updates of plugins made by colleagues.

## Output of `gemini --version`: 

5.0.0-alpha.6

## Contents of `.gemini.yml` file:

```yaml
system:
  plugins:
    html-reporter:
      enabled: true
      path: gemini-report
      errorsOnly: false
```

Result:
```
Critical error:
UnknownKeysError: Unknown options: root.errorsOnly
exited
```

Expected:
```
Warning! Check this:
UnknownKeysError: Unknown options: root.errorsOnly
... continuing execution
```
