### ISSUE TITLE
ReferenceError: data is not defined

### ISSUE THREAD

**Issue by ganlanyuan** [gemini-testing/html-reporter#21]
Every time I run `gemini test` or `gemini` update, I get this error:
```
Critical error:
ReferenceError: data is not defined
    at Object.<anonymous> (/Users/.../gemini/gemini-reports/bundle.min.js:1:100215)
    at Object.defineProperty.value (/Users/.../gemini/gemini-reports/bundle.min.js:1:100357)
    at n (/Users/.../gemini/gemini-reports/bundle.min.js:1:163)
    at Object.<anonymous> (/Users/.../gemini/gemini-reports/bundle.min.js:1:75605)
    at n (/Users/.../gemini/gemini-reports/bundle.min.js:1:163)
    at n (/Users/.../gemini/gemini-reports/bundle.min.js:1:513)
    at Object.<anonymous> (/Users/.../gemini/gemini-reports/bundle.min.js:1:522)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.exports.requireWithNoCache (/Users/.../node_modules/gemini/lib/utils.js:5:12)
    at _.forEach (/Users/.../node_modules/gemini/lib/test-reader.js:19:15)
    at /Users/.../node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/Users/.../node_modules/lodash/lodash.js:3001:24)
    at /Users/.../node_modules/lodash/lodash.js:4913:18
    at Function.forEach (/Users/.../node_modules/lodash/lodash.js:9359:14)
    at loadSuites (/Users/.../node_modules/gemini/lib/test-reader.js:15:7)
    at SetsBuilder.create.useSets.useFiles.useBrowsers.build.then (/Users/.../node_modules/gemini/lib/test-reader.js:35:34)
```

But before I use `html-reporter`, everything was fine.

**Comment by j0tunn** [comment]
@DudaGod take a look please

**Comment by j0tunn** [comment]
@ganlanyuan Can you tell us which version of gemini and html-reporter you use and show your config

**Comment by ganlanyuan** [comment]
gemini: 5.0.0-alpha.8
html-reporter: 0.7.0

.gemini.yml:
```yml
rootUrl: 'http://localhost:8888'
# screenshotsDir: './screens'
# windowSize: 600x400
compositeImage: true

system:
  plugins:
    browserstack:
      username: 'xxx'
      accessKey: 'xxx'
    'html-reporter':
      enabled: true
      path: './gemini/gemini-reports'
      errorsOnly: false
      baseHost: 'http://localhost:8888'
 
browsers:
  ie11:
    windowSize: 600x400
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'internet explorer'
      version: '11'
 
  chrome43:
    windowSize: 1024x768
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '10'
      browserName: 'chrome'
      version: '43'
```

**Comment by DudaGod** [comment]
Hello.

Can you check if you have a file named `data.js` in the folder `your-project/gemini/gemini-reports` and if yes - send please its content

**Comment by ganlanyuan** [comment]
`./gemini/gemini-reports/data.js`:
```js
var data = {"skips":[],"suites":[{"name":"jumbotron","suitePath":["jumbotron"],"children":[{"name":"plain","suitePath":["jumbotron","plain"],"browsers":[{"name":"chrome43","result":{"suiteUrl":"http://localhost:8888/","name":"chrome43","metaInfo":"{\n    \"url\": \"/\",\n    \"file\": \"gemini/test1.js\",\n    \"sessionId\": \"43b9896a17f6c438345831145fdc03aa896488f7\"\n}","success":true,"actualPath":"images/jumbotron/plain/chrome43~current.png","expectedPath":"images/jumbotron/plain/chrome43~ref.png"},"retries":[]},{"name":"ie11","result":{"suiteUrl":"http://localhost:8888/","name":"ie11","metaInfo":"{\n    \"url\": \"/\",\n    \"file\": \"gemini/test1.js\",\n    \"sessionId\": \"db7a4c2384436c0227faa2e5ff8ccdf5b064dc1a\"\n}","success":true,"actualPath":"images/jumbotron/plain/ie11~current.png","expectedPath":"images/jumbotron/plain/ie11~ref.png"},"retries":[]}]}]}],"errorsOnly":false,"baseHost":"http://localhost:8888","total":2,"updated":0,"passed":2,"failed":0,"skipped":0,"warned":0,"retries":0};
try { module.exports = data; } catch(e) {}
```

**Comment by DudaGod** [comment]
I understood what happens.

Look, you have your tests in the `./gemini/` folder and generated files from html-reporter you saved to `./gemini/gemini-reports` which contains two files with `.js` extension. In next run `gemini test` or `gemini update` will read all tests from your `gemini` folder with `.js` extension. So it will even read `./gemini/gemini-reports/build.min.js` and in the process of interpretation of this file it don't find `data` variable because it connected separately in `index.html` and available only on browser page through window scope.

I have few solutions of your problem:
1) use exclude (read about it [here](https://gemini-testing.github.io/doc/config.html)):
```js
system:
  exclude:
    - 'gemini/gemini-reports/**'
```

2) use sets (read about it [here](https://gemini-testing.github.io/doc/config.html)):
```js
sets:
  desktop:
    files:
      - 'gemini/tests/desktop/**'
    browsers:
      - ie11
      - chrome43
```

**Comment by DudaGod** [comment]
Let us know if it helped you.

**Comment by ganlanyuan** [comment]
Thanks @DudaGod 
The first solution doesn't work with the following config:
```yml
rootUrl: 'http://localhost:8888'
# screenshotsDir: './screens'
# windowSize: 600x400
compositeImage: true             # fix "The region bottom bound is outside of the viewport height"

system:
  exclude:
    - 'gemini/gemini-reports/**'
    - 'node_modules/**'
  plugins:
    browserstack:
      username: 'xxx'
      accessKey: 'xxx'
    'html-reporter':
      enabled: true
      path: './gemini/gemini-reports'
      errorsOnly: false
      baseHost: 'http://localhost:8888'
 
browsers:
  ie11:
    windowSize: 600x400
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'internet explorer'
      version: '11'
 
  chrome43:
    windowSize: 1024x768
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '10'
      browserName: 'chrome'
      version: '43'
```

With the second solution:
```yml
rootUrl: 'http://localhost:8888'
# screenshotsDir: './screens'
# windowSize: 600x400
compositeImage: true             # fix "The region bottom bound is outside of the viewport height"

system:
  # exclude:
  #   - 'gemini/gemini-reports/**'
  #   - 'node_modules/**'
  plugins:
    browserstack:
      username: 'xxx'
      accessKey: 'xxx'
    'html-reporter':
      enabled: true
      path: './gemini/gemini-reports'
      errorsOnly: false
      baseHost: 'http://localhost:8888'
 
browsers:
  ie11:
    windowSize: 600x400
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'internet explorer'
      version: '11'
 
  chrome43:
    windowSize: 1024x768
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '10'
      browserName: 'chrome'
      version: '43'

sets:
  desktop:
    files:
      - 'gemini/gemini-reports/desktop'
    browsers:
      - ie11
      - chrome43
```
I got the following result:
```
gemini update
Opening BrowserStack tunnel.
Total: 0 Passed: 0 Failed: 0 Skipped: 0 Retries: 0
Closing BrowserStack tunnel.
Your HTML report is here: file:///Users/xxx/gemini/gemini-reports/desktop/index.html
```
Seems didn't run any test at all.
